# Configure Zencoder gem to use our custom transcoder service
require 'zencoder'

# Configure Zencoder immediately for worker processes  
Zencoder.base_url = ENV.fetch('TRANSCODER_BASE_URL', 'http://pageflow_transcoder:8080')

Pageflow.configure do |config|
  # The email address to use as from header in invitation mails to new
  # users.
  config.mailer_sender = 'change-me-at-config-initializers-pageflow@example.com'

  # Entry type plugins
  config.plugin(PageflowPaged.plugin)
  config.plugin(PageflowScrolled.plugin)

  # Plugins that provide page types and widget types.
  config.plugin(Pageflow.built_in_page_types_plugin)
  config.plugin(Pageflow.built_in_widget_types_plugin)
  # config.plugin(Pageflow::Rainbow.plugin)

  config.for_entry_type(PageflowPaged.entry_type) do |entry_type_config|
    # Add custom themes by invoking the pageflow:theme generator and
    # registering the theme here.
    #
    #     $ rails generate pageflow:theme my_custom_theme
    #     => creates app/assets/stylesheets/pageflow/themes/my_custom_theme.css.scss
    #
    entry_type_config.themes.register(:default)
    # config.themes.register(:my_custom_theme)
  end

  # String to interpolate into paths of files generated by paperclip
  # preprocessors. This allows to refresh cdn caches after
  # reprocessing attachments.
  config.paperclip_attachments_version = 'v1'

  # Allow multiple development instances to share one S3 bucket by
  # keeping each instance's files in a separate folder named after the
  # system's hostname. Use a generic `main` folder in all other
  # environments.
  config.paperclip_s3_root =
    if Rails.env.development?
      require 'socket'
      Socket.gethostname
    else
      'main'
    end

  # How to handle https requests for URLs which will have assets in the page.
  # If you wish to serve all assets over http and prevent mixed-content warnings,
  # you can force a redirect to http. The inverse is also true: you can force
  # a redirect to https for all http requests.
  #
  #     config.public_https_mode = :prevent (default) # => redirects https to http
  #     config.public_https_mode = :enforce # => redirects http to https
  #     config.public_https_mode = :ignore # => does nothing
  config.public_https_mode = :ignore

  # Rewrite the below section to use your favorite configuration
  # method: ENV variables, secrets.yml, custom yml files. If you use
  # environment variables consider the dotenv gem to configure your
  # application via a single .env file.
  #
  # Whatever you choose, do NOT hard code values below. That makes it
  # hard to switch environments and risks leaking secrects.

  # Default options for paperclip attachments which are supposed to
  # use s3 storage. All options allowed in paperclip has_attached_file
  # calls are allowed.
  #
  # MinIO S3-Compatible Storage Configuration:
  # - Uses internal endpoint for server-side operations (Docker hostname)
  # - External endpoint/host used by client browsers for direct uploads
  # - Falls back to internal endpoint if external not configured
  
  # S3 Endpoint Configuration
  # Internal endpoint: Workers connect to MinIO using Docker service name
  internal_endpoint = ENV.fetch('S3_ENDPOINT_INTERNAL', 'http://pageflow_minio:9000')
  
  # External endpoint: Browsers connect to MinIO using external host (configurable)
  external_endpoint = ENV.fetch('S3_ENDPOINT_EXTERNAL', "http://localhost:#{ENV.fetch('MINIO_API_HOST_PORT', '9000')}")
  external_host = external_endpoint.gsub(%r{https?://}, '')
  
  # For server-side operations, always use internal Docker hostname
  server_endpoint = internal_endpoint
  
  # For client-side operations, use external endpoint
  client_host = external_host
  client_endpoint = external_endpoint
  
  config.paperclip_s3_default_options.merge!(
    s3_credentials: {
      bucket: ENV.fetch('S3_BUCKET', 'pageflow-main'),
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID', 'minioadmin'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY', 'minioadmin123')
    },
    s3_host_name: server_endpoint.gsub(%r{https?://}, ''),
    s3_region: ENV.fetch('AWS_REGION', 'us-east-1'),
    s3_host_alias: "#{client_host}/#{ENV.fetch('S3_BUCKET', 'pageflow-main')}",
    s3_protocol: ENV.fetch('S3_PROTOCOL', 'http'),
    s3_options: {
      endpoint: server_endpoint,
      force_path_style: ENV.fetch('S3_FORCE_PATH_STYLE', 'true') == 'true'
    }
  )

  # Default options for paperclip attachments which are supposed to
  # use filesystem storage. All options allowed in paperclip has_attached_file
  # calls are allowed.
  # Custom Transcoder Service Configuration
  # Using our GPU-accelerated transcoder service with Zencoder API compatibility
  config.zencoder_options.merge!(
    api_key: ENV.fetch('TRANSCODER_SERVICE_KEY', 'pageflow-transcoder'),
    output_bucket: ENV.fetch('S3_OUTPUT_BUCKET', 'pageflow-output'),
    s3_host_alias: "#{client_host}/#{ENV.fetch('S3_OUTPUT_BUCKET', 'pageflow-output')}",
    s3_protocol: ENV.fetch('S3_PROTOCOL', 'http'),
    attachments_version: 'v1',

    # Zencoder can generate SMIL files which can be used to have
    # Akamai generate HLS-playlists. By default, Pageflow makes
    # Zencoder generate HLS-playlists. To prevent hitting Zencoder's
    # 20 outputs limit, we disable smil outputs.
    skip_smil: true
  )

  # Direct uploads configuration for MinIO using presigned POST
  # This generates proper presigned POST URLs with form fields for browser uploads
  config.paperclip_direct_upload_options = lambda do |attachment|
    max_upload_size = 4_294_967_296 # max file size in bytes (4GB)
    
    # Create S3 client for external endpoint (browser access)
    require 'aws-sdk-s3'
    s3_client = Aws::S3::Client.new(
      endpoint: external_endpoint,
      access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID', 'minioadmin'),
      secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY', 'minioadmin123'),
      region: ENV.fetch('AWS_REGION', 'us-east-1'),
      force_path_style: ENV.fetch('S3_FORCE_PATH_STYLE', 'true') == 'true'
    )
    
    # Create S3 resource to get bucket object
    s3_resource = Aws::S3::Resource.new(client: s3_client)
    bucket = s3_resource.bucket(ENV.fetch('S3_BUCKET', 'pageflow-main'))
    
    # Generate presigned POST configuration
    presigned_post_config = bucket.presigned_post(
      key: attachment.path,
      success_action_status: '201',
      acl: 'public-read',
      content_length_range: 0..max_upload_size
    )
    
    {
      url: presigned_post_config.url,
      fields: presigned_post_config.fields
    }
  end

  # Used to encrypt stored access tokens.
  config.encryption_options.merge!(
    key: ENV.fetch('SYMMETRIC_ENC_KEY', '1234567890ABCDEF'),
    iv: ENV.fetch('SYMMETRIC_ENC_IV', '1234567890ABCDEF')
  )

  # Specify default meta tags to use in published stories.
  # These defaults will be included in the page <head> unless overriden by the Entry.
  # If you set these to <tt>nil</tt> or <tt>""</tt> the meta tag won't be included.
  config.default_keywords_meta_tag = 'pageflow, multimedia, reportage'
  config.default_author_meta_tag = 'Pageflow'
  config.default_publisher_meta_tag = 'Pageflow'
end

# Additional Zencoder configuration that runs after Pageflow's own configuration
Pageflow.after_global_configure do |config|
  # Ensure our custom transcoder URL isn't overridden by main app
  Zencoder.base_url = ENV.fetch('TRANSCODER_BASE_URL', 'http://pageflow_transcoder:8080')
  Rails.logger.info "🔄 Zencoder configured for custom transcoder: #{Zencoder.base_url}"
end

# Comment out this call if you wish to run rails generators or rake
# tasks while the Pageflow configuration is in an invalid
# state. Otherwise Pageflow configuration errors might prevent you
# from initializing the environment. Required for Pageflow to run.
Pageflow.finalize!
